name: Check for changes that require running the rest of the CI

on:
  workflow_call:
    inputs:
      directories:
        description: 'The directories to check for changes'
        required: true
        type: string
    outputs:
      has_changes:
        description: 'Whether changes were found or not (yes/no)'
        value: ${{ jobs.check.outputs.has_changes }}

jobs:
  check:
    env:
      # put the list of directories to watch for changes here, convert to space-separated list
      watch_list: "${{ join(fromJson(inputs.directories), ' ') }}"
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}
    steps:
      - id: fetch
        name: Fetch current branch
        uses: actions/checkout@v4.1.1

      - id: check
        name: Check for changes
        run: |
          echo "Checking for changes in ${{ env.watch_list }}"
          if git diff --quiet HEAD^ HEAD ${{ env.watch_list }}; then
            echo "has_changes=yes" >> $GITHUB_ENV
          else
            echo "has_changes=no" >> $GITHUB_ENV
          fi
